apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  type: LoadBalancer #The only difference from clusterip
  selector: #The service attaches to the pod by matching with the labels
    env: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: {{ .Values.service.port }} #This port number belongs to service
    targetPort: nginx-port #This port number belongs to container