--To monitor disk usage = df -hT | awk '{print $6}' | cut -d% -f1
    1. df -hT = shows disk usage with filesystem type.
    2. In its output, the Use% column (e.g., 45%) is in the 6th field, not the 5th.
    3. awk '{print $6}' = prints that column.
    4. cut -d% -f1 = removes the % sign, leaving just the number

--[ec2-user@ip-172-31-20-206 ~]$ sudo systemctl is-active docker
active
--[ec2-user@ip-172-31-20-206 ~]$ sudo systemctl is-active docker --quiet
--[ec2-user@ip-172-31-20-206 ~]$ sudo systemctl is-active docker

--Code to check if docker is active and activate it = 
#!/bin/bash
if !systemctl is-active docker --quiet nginx; then
echo "service down"
systemctl start nginx
fi

--On command line = 
    1. ! systemctl is-active --quiet nginx && echo "nginx service down" && systemctl start nginx
    2. for svc in docker nginx; do ! systemctl is-active --quiet $svc && echo "$svc service down" && systemctl start $svc; done

--Logs are files or records automatically generated by an operating system, application, service, or device to keep track of events, activities, errors, or status information.
    1. They are like a diary or black box of a system that helps administrators, developers, and security teams understand what happened and when.
    2. Example = nginx → /var/log/nginx/access.log
    3. System Logs = Recorded by the OS (Linux/Windows). Examples: /var/log/syslog (general system messages)
    4. Database Logs = Example: /var/log/mysql/error.log

--code to find logs older than 7 days, compress them = File+Type+Name+Mtime+Exec
    1. find "$LOG_DIR" -type f -name "*.log" -mtime +7 -exec gzip {} \;
    2. 
    3. LOG_DIR="/var/log/myapp" 
    4. -type f = Only match files (not directories).
    4. -name "*.log" = Only pick files ending with .log. 
    5. -mtime +7 = Select files modified more than 7 days ago. 
    5. -exec gzip {} \; = For every file found, execute the command gzip {}.
        gzip = Compresses the log file. Example: app.log → becomes app.log.gz (and deletes the original).
        {} = placeholder replaced with the filename found by find.
        \; = tells find that this is the end of the -exec command.


--code to rotate logs and delete logs older than 30 days = 
    1. find "$ARCHIVE_DIR" -type f -name "*.log.gz" -mtime +30 -exec rm {} \;

--If you want a code to run automatically, you can add it to cron = 0 2 * * * /usr/local/bin/logrotate.sh

--How to automate the transfer of files from a local machine to a remote server using scp(secure copy) = 
    1. To copy a file from local to remote: scp /pathtolocalfile username@remotehostIP:/path/to/remote/directory/
    2. To copy a directory: scp -r /path/to/local/dir username@remote_host:/path/to/remote/directory/

--To Add a user to an existing group = usermod -aG groupname username 
    1. -a = append (don’t remove from other groups)
    2. -G = specify the group(s)
    3. Check user’s groups = groups username

--Reboot the system = sudo reboot
