version: 0.2

env:
  parameter-store:
    para: dockercred
  variables:
    user: "cryl91@gmail.com"
    pass: "Cyril"
phases:
  install:
    runtime-versions:
      python: 3.11 #choose the language in which the program is written in.
  pre_build:
    commands: #Installing the dependencies
      - pip install -r ZPython/requirements.txt
  build:
    commands:
      - cd ZPython/
      - echo "Building Docker Image"
      - echo $pass | docker login -u $user --password-stdin
      - docker build -t "cryl91/$para:1" .
      - docker push "cryl91/$para:1"
  post_build:
    commands:
      - echo "Build is successful"
      