apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations: 
    com.project.author: production
    com.project.name: web
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80