apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: demo
      value: "Hello from the env"
    - name: demo1
      value: "new demo"  