apiVersion: v1
kind: Pod
metadata:
  name: envconfig
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom: 
        configMapKeyRef:
          name: configmap
          key: course
    - name: Person
      valueFrom: 
        configMapKeyRef:
          name: configmap
          key: duration
    - name: Trainer
      valueFrom: 
        configMapKeyRef:
          name: configmap
          key: trainer