apiVersion: v1
kind: Pod
metadata:
  name: envconfig
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: course
      valueFrom: 
        configMapKeyRef:
          name: configmap
          value: course
    - name: Person
      valueFrom: 
        configMapKeyRef:
          name: configmap
          value: duration
    - name: Trainer
      valueFrom: 
        configMapKeyRef:
          name: configmap
          value: trainer