apiVersion: v1
kind: Pod
metadata:
  name: envconfig
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    envFrom: #This will refer all the configmap values
    - configMapRef:
        name: configmap

