#In AWS EKS when you create a Load Balancer service an AWS Classic Load Balancer (CLB) or Network Load Balancer (NLB) by default. You’ll get an NLB or CLB (depending on EKS setup)
#If you want an Application Load Balancer (ALB), you don’t use Service directly, you use the AWS Load Balancer Controller + Ingress.
#Login in to one more container and curl ip/servicename. To get ip = kubectl get services 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    env: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #To always pull the latest image
    ports:
    - containerPort: 80
      name: nginx-port
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  type: LoadBalancer #The only difference from clusterip
  selector: #The service attaches to the pod by matching with the labels
    env: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 #This port number belongs to service
    targetPort: nginx-port #This port number belongs to container