pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    environment {
    user = 'abc'
    }
    parameters {
         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    stages {
        stage('build') {
            steps {
            script{
            def docker = "car"
            echo "building and ${user} and ${params.PERSON} & ${docker}"
            sh 'pwd'
            sh '''
            ls -l
            '''
            }
            }
            
        }

        }
    
        post {
            always {
                echo "I will run everytime"
            }

            success {
                echo "I will run only on success"
            }
            failure {
                echo "I will run only on failure"
            }
        }
}