pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    environment {
    user = 'abc'
    }
    parameters {
         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    stages {
        stage('build') {
            environment {
                user = "cdf"
            }
            steps {
            script{//Use script to define variables in groovy
            def docker = "car"
            echo "building and ${user} and ${params.PERSON} & ${docker}"
            sh 'pwd' //Output = /var/lib/jenkins/workspace/Linux
            sh '''
            cd ../..
            ls -ltr
            '''
            }
            }
            
        }
        //In Jenkins, a job (sometimes called a project) is basically a unit of work that Jenkins runs. It’s what you create on the Jenkins dashboard when you click “New Item”.
        stage('Test') {
            environment {
            MY_SECRET = credentials('abcde')
            }
            steps {
            //build job: 'my-other-job' → Name of the Jenkins job you want to trigger. "Build job: 'my-other-job', wait: false". Here wait: false = Supports waiting for completion (default) or fire-and-forget.
            //build job: 'abcde', wait: false //runs another Jenkins job named 'abcde' ie create a new Item -> pipeline -> from git a jenkinsfile.
            sh '''
            echo "Testing and $MY_SECRET"
            ls -ltr
               '''
            }
            
        }
        stage('Deploy') {
            steps { //To see other folders move from Linux folder = cd 1Linux/ or cd 2Ansible/  
            withCredentials([string(credentialsId: 'abcd', variable: 'TOKEN')]) {
                    sh '''
                      echo "Using secret token $TOKEN"
                    '''
                }
            sh ''' 
            echo "Deploying"
            cd 1Linux/ 
            ls -ltr
               '''
            }
            
        }
        
        stage('Parallel Tasks') {
        parallel { 
            stage('Parallel 1') {
                steps {
                    echo 'Parallel 1 Executed'
                }
            }
            stage('Parallel 2') {
                steps {
                    echo 'Parallel 2 Executed'
                    }
                }
            }
        }

        }
    
        post {
            always {
                echo "I will run everytime"
            }

            success {
                echo "I will run only on success"
            }
            failure {
                echo "I will run only on failure"
            }
        }
}