pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    environment {
    user = 'abc'
    }
    parameters {
         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    stages {
        stage('build') {
            environment {
                user = "cdf"
            }
            steps {
            script{//Use script to define variables in groovy
            def docker = "car"
            echo "building and ${user} and ${params.PERSON} & ${docker}"
            sh 'pwd'
            sh '''
            cd ../..
            ls -ltr
            '''
            }
            }
            
        }
        stage('Test') {
            steps {
            sh '''
            echo "Testing"
            ls -ltr
               '''
            }
            
        }
        stage('Deploy') {
            steps {
            sh '''
            echo "Deploying"
            cd 1Linux/
            ls -ltr
               '''
            }
            
        }
        
        stage('Parallel Tasks') {
        parallel { 
            stage('Parallel 1') {
                steps {
                    echo 'Parallel 1 Executed'
                }
            }
            stage('Parallel 2') {
                steps {
                    echo 'Parallel 2 Executed'
                    }
                }
            }
        }

        }
    
        post {
            always {
                echo "I will run everytime"
            }

            success {
                echo "I will run only on success"
            }
            failure {
                echo "I will run only on failure"
            }
        }
}