apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static  
spec:
  storageClassName: "" #Used in Dynamic Provisioning
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4 
    volumeID: vol-031fc31712fab5fe6
  capacity:
    storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: #These labels are deployment set labels.Every k8s resources have labels
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 10
  selector: #selector should match with template. The selector should match with pod labels
    matchLabels:
      tier: frontend
      env: prod
  template: #Template is pod labels   
    metadata:
      labels:
        tier: frontend
        env: prod
    spec:
      containers: 
      - name: nginx
        image: nginx:latest
        ports: 
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:    
          claimName: ebs-static-pvc


