#Deployment code is put here.apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: Catalogue
  labels: #These labels are deployment set labels.Every k8s resources have labels
    app: catalogue
    tier: app
spec:
  # modify replicas according to your case
  replicas: 2
  selector: #selector should match with template. The selector should match with pod labels
    matchLabels:
      app: catalogue
      tier: app
  template: #Template is pod labels   
    metadata:
      labels:
        app: catalogue
        tier: app
    spec:
      containers: 
      - name: catalogue
        image: catalogue:1.0
---
#Setting up a clusterip to connect catalogue to web
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    env: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 #This port number belongs to service
    targetPort: nginx-port #This port number belongs to container