#Deployment code is put here.apiVersion: apps/v1
kind: Deployment
metadata:
  name: Catalogue
  namespace: roboshop
  labels: #These labels are deployment set labels.Every k8s resources have labels
    app: catalogue
    tier: app
spec:
  # modify replicas according to your case
  replicas: 2
  selector: #selector should match with template. The selector should match with pod labels
    matchLabels:
      app: catalogue
      tier: app
  template: #Template is pod labels   
    metadata:
      labels:
        app: catalogue
        tier: app
    spec:
      containers: 
      - name: catalogue
        image: joindevops/catalogue:1.0
        envFrom:
        - configMapRef:
            name: configmap
---
#Setting up a clusterip to connect catalogue to web
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    env: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080 #This port number belongs to service
    targetPort: 8080 #This port number belongs to container
---
#Create a configmap to pass variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: roboshop
data:
  MONGO: "true" #keep true in double quotes 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
