#To directly label nodes = Kubectl label nodes nodename env=dev
#To filter based on labels = kubectl logs -l name=mylabel
apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels: 
    envirnoment: production2
    app: web
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80