- name: vars
  hosts: web
  become: yes
  vars:
    course: devops
    duration: 1hr
  tasks: 
  - name: Print Variables 
    ansible.builtin.debug:
      msg: "The course is {{course}},the duration is {{duration}}"
  - name: Print Inheritance Variables 
    vars:
    - course: development
    ansible.builtin.debug:
      msg: "The course is {{course}},the duration is {{duration}}"
  - name: Print Variables from inventory 
    ansible.builtin.debug:
      msg: "The course is {{mongo_username}},the duration is {{mongo_password}}"
