apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    imagePullPolicy: Always #To always pull the latest image
    ports:
    - containerPort: 8081

