#Command to run = docker-compose up -d
#Use the host’s IP address, not the container’s IP, even on a custom bridge. 
#You’re mapping container’s port to the host with -p, and that’s what makes it reachable via browser.
networks:
  roboshop:
    driver: bridge
services: 
  web:
    image: web:1
    container_name: web
    networks: 
      - roboshop
    ports: 
      - "80:80"
    # environment:
    #   - user=roboshop
    #   - pass=roboshop123
    # depends_on:
    #   - catalogue
    #   - user 