apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: #These labels are deployment set labels.Every k8s resources have labels
    app: nginx
    tier: web
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicasCount }} #Dont give double quotes for numbers. Use it only for alphabets
  selector: #selector should match with template. The selector should match with pod labels
    matchLabels:
      tier: nginx
      env: web
  template: #Template is pod labels   
    metadata:
      labels:
        tier: nginx
        env: web
    spec:
      containers: 
      - name: nginx
        image: "nginx:{{ .Values.deployment.imageVersion }}"
        ports: 
        - containerPort: 80
