#nodeSelector always expects a key–value pair of labels. So: 
  #1. Add a label to node: kubectl label node ip-192-168-10-94.ec2.internal role=frontend
  #2. kubectl get nodes --show-labels

apiVersion: v1
kind: Pod
metadata:
  name: firstnode
spec:
  nodeName: ip-192-168-10-94.ec2.internal
  containers:
  - name: nginx1
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: secondnode
spec:
  nodeName: ip-192-168-61-165.ec2.internal
  containers:
  - name: nginx2
    image: nginx
    ports:
    - containerPort: 80  