apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels: 
    env: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2 #Kubernetes will pull the nginx:1.14.2 image from Docker Hub by default. Kubernetes defaults to docker.io (Docker Hub) when no registry is provided
    imagePullPolicy: Always #To always pull the latest image
    ports:
    - containerPort: 80 
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    hostPath: #Gives access to /var/log from the node
      path: /var/log 
#If you wanted the image from another registry, you’d explicitly set it, e.g.: image: myregistry.example.com/custom-nginx:1.14.2
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: roboshop #Since kubectl matches Services to Pods within the same namespace, they won’t connect unless both are in roboshop
spec:
  type: NodePort #The only difference from clusterip
  selector: #The service attaches to the pod by matching with the labels
    env: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 #This port number belongs to service
    targetPort: 80 #This port number belongs to container
    nodePort: 30080  # External port on node (must be 30000–32767)
#To see node External IPs = kubectl get nodes -o wide
#To login in = http://<External NodeIP>:30080
    