apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2 #Kubernetes will pull the nginx:1.14.2 image from Docker Hub by default. Kubernetes defaults to docker.io (Docker Hub) when no registry is provided
    imagePullPolicy: Always #To always pull the latest image
    ports:
    - containerPort: 80

