apiVersion: v1
kind: Pod
metadata:
  name: envconfig
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course #A name given to the configmap value
      valueFrom: 
        configMapKeyRef:
          name: configmap #The name of the configmap
          key: course
    - name: Person 
      valueFrom: 
        configMapKeyRef:
          name: configmap 
          key: duration
    - name: Trainer
      valueFrom: 
        configMapKeyRef:
          name: configmap
          key: trainer