apiVersion: v1
kind: Secret
metadata:
  name: secret-info
data:
  username: SDEK
  password: SDEK #Encode using base64 and paste the value here 
---
apiVersion: v1
kind: Pod
metadata:
  name: envsecrets
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: username
      valueFrom:  
        secretKeyRef:
          name: secret-info 
          key: username 
    - name: password
      valueFrom: 
        secretKeyRef:
          name: secret-info
          key: password
#To get all secrets at once: 
    # envFrom: 
    # - secretRef:
    #     name: secret-info