apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: guestbook
    tier: frontend
spec:
  replicas: 3 #You can change this to see argocd changes automatically
  selector: 
    matchLabels:
      tier: frontend
      env: prod
  template:  
    metadata:
      labels:
        tier: frontend
        env: prod
    spec:
      containers: 
      - name: nginx
        image: nginx:latest
        ports: 
        - containerPort: 80
