- name: Nginx
  hosts: web
  tasks: 
  - name: Install Nginx
    ansible.builtin.nginx:
      name: nginx
      state: installed
  - name: Install Nginx
    ansible.builtin.service:
      name: nginx
      state: started


