- name: vars
  hosts: localhost #managing the ansible server itself. If its localhost then you dont need to give username and password through ansible command line
  become: yes
  vars_files:
    vars.yaml
  tasks: 
  - name: Print Variables 
    ansible.builtin.debug:
      msg: "The course is {{course}},the duration is {{duration}}"

