#A hostPath volume mounts a directory or file from the node's filesystem into the container.
apiVersion: apps/v1
kind: DaemonSet #Ensures one pod in every worker node
metadata:
  name: fluentd
  namespace: kube-system #Admin Namespace
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      containers:
      - name: fluentd
        #image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath: #Gives access to /var/log from the node
          path: /var/log 