apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb-stateful # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongodb-stateful # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb-stateful
        image: mongodb 
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /data/db
  #This is pvc directly.  
  volumeClaimTemplates:
  - metadata:
      name: ebs-static-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-stateless #To make stateful set as headless service
spec:
  clusterIP: None #To make it a headless service give this
  selector:
    app: mongodb-stateful
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 27017 #This port number belongs to service
    targetPort: 27017 #This port number belongs to container